# Generated by Django 2.0.2 on 2018-02-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['qual_type'],
            },
        ),
    ]
